### ISSUE TITLE
Label of graph does not change when you toggle different values

### ISSUE THREAD

**Issue by ellawatkinsdulaney** [palmhjell/ninetysix#1]
![image](https://user-images.githubusercontent.com/85522804/125540182-f11674c5-ecb3-4b55-b6ac-8416b74eca4c.png)

If I toggle different lysis times, the title stays constant at 30 min. This may be a function of trying to groupby many things using your method, I know your example only has groupby for one item.

I would say this is an enhancement request(?)

**Comment by palmhjell** [comment]
This should work as you want it to. It might be something weird with the lysis time column being object or string dtype (just assuming, since otherwise it should default to a slider, not a toggle), or a version issue?

For example, all my plot titles change properly here with two groupby arguments:
<img width="1017" alt="image" src="https://user-images.githubusercontent.com/35536435/125540685-012b0d92-4523-4b06-9940-c8cabc2e67ac.png">

Try the following code and tell me if it works or doesn't:
```python
# Seed
np.random.seed(8675309)

# A1-H12 wells
wells = [row+str(col)
         for row in list('ABCDEFGH')
         for col in range(1, 13)]

# Create a list of five plates
plates = []
for i in range(1, 6):
    
    # Generate random distribution of values and make Plate
    values = np.random.normal(10+i, 2, size=len(wells))
    plate = ns.Plate(zip(wells, values))
    
    # Add the annotation `plate` = i
    plate['plate'] = i
    
    # Set `plate` as a location (not necessary)
    plate = plate.set_as_location('plate', idx=0)
    
    # Add control annotations
    controls = {
        '[A-D]10': 'standard',
        'E10': 'empty',
        '[F-H]10': 'negative',
        'other': 'experiment',
    }
    plate = plate.annotate_wells({'controls': controls})
    
    # Append only the DataFrame to work with pd.concat
    plates.append(plate.df)
    locations = plate.locations
    values = plate.values

# Create new Plate object
plates = ns.Plate(pd.concat(plates).reset_index(drop=True))

# Update attributes
plates.locations = locations
plates.values = values

# Normalize each plate on its own and change prefix
plates = plates.normalize(
    to='controls=standard',
    zero='controls=negative',
    groupby='plate',
    prefix='norm '
)

# Plot with two groupby args
plates.plot_rof(groupby=['plate', 'row'])
```

**Comment by ellawatkinsdulaney** [comment]
I re-ran the code after pulling 0.0.5 and it is fully functional! Thank you!
